spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: '{cipher}74b09724a7f94d0a0d7bb0366b5071bb8f9ed5f71154c28154a226d107d982f6'

token:
  expiration_time: 86400000
  secret: userservice_yml_secret_token

gateway:
  ip: 127.0.0.1