server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:\\Users\\1700\\Documents\\cloud-config
        git:
          uri : file:///C:\\Users\\1700\\Documents\\cloud-config
#          uri : https://github.com/shhhsip/SpringCloudPratice.git
          default-label: main
          search-paths: cloud-config # root가 아닌 하위 디렉토리에 위치한 경우


management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh # configserver에 변경사항이 있으면 rabbitmq를 통해 변경사항을 푸쉬

#파일 시스템에 저장하여 사용하는 방법
#spring:
#  application:
#    name: config-service
#  cloud:
#    config:
#      server:
#        native:
#
#        git:
#          #uri: file:///${user.home}\\Documents\\git-local-repo
#          default-label: main

